FROM ubuntu
RUN touch file1 file2 aws
RUN HELLO THIS IS EXTRA DATA WE ARE ADDING TO THIS FILE
RUN ADDING SOME MORE CONTENT
RUN THIS IS JENKINS CLASS, THANKS FOR JOINING
RUN 475683973023@#$%^&*()
RUN ADDING SOME NEW CONTENT BY DEV-4
